# Generated by Django 5.2.13 on 2026-04-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='body_type',
            new_name='type',
        ),
    ]
